### PR TITLE
Fix Compilation

### LINKED ISSUE #11: Use of undeclared type 'ConflictResolution
I am having the Swift Compiler error: Use of undeclared type 'ConflictResolution for the GameCollecgtion.swift and GameControllerInputMapping.swift files while compiling for IOS 12.0 Is there any fix for this??

### PR DESCRIPTION
**Pull request by valeIT**
I'm not sure on which conflict resolution would be the preferred so I went with .local for now. This fixes all the compilation issues I had on my machine.

Fixes #11

### CODE REVIEW

**Comment by dcvz** [comment]
My guess is that @rileytestut forgot to push some new changes into the Harmony repository. The commits both the `Harmony` & `Roxas` submodules are linked to, don't exist in their respective repositories.

**Comment by yardiboy** [comment]
Delta.xcodeproj/project.xcworkspace/contents.xcworkspacedata

**Comment by yardiboy** [comment]
I'm not sure on which conflict resolution would be the preferred so I went with .local for now. This fixes all the compilation issues I had on my machine.

**Comment by yardiboy** [comment]
conflict resolution would be the preferred so I went with .local for This fixes all the compilation issues I had on my machine.

**Comment by yardiboy** [comment]
Man thank you mide TL Mert yok

**Pull request closed without merging**
