### PR TITLE
Feature: Appearance Menu (App Icons, App Color, Page Control Indicator)

### PR DESCRIPTION
**Pull request by ianclawson**
I closed the App Icon PR (https://github.com/rileytestut/Delta/pull/130) in favor of this, once I realized I was also working two other appearance-related features. Now all three coexist within the same submenu rather than all taking more room on the base Settings menu!

(unfortunately it does mean this PR is larger than ideal. If it's preferred that this be split up into 3 separate PRs, I'm happy to do so)

Notes:
* Use of the Color Picker VC is locked to >= iOS 14, so this feature is not available for all users. It's possible to update so that on < iOS 14 there are color options (such as a hex color text input, or preset option) in place of a Color Picker, but I forewent that in favor of not bloating the PR further.
* Use of the page control API requires >= iOS 14, so this feature is not available for all users, and unfortunately the only way around that would be to write a custom implementation.

Trello cards:
* App Icon: https://trello.com/c/lBhuBBj4
* App Color: https://trello.com/c/9TFZvmaf
* Page Control Indicator Images: https://trello.com/c/VIDNLMIO

Screenshots:
IMG_4B6FA0B6244B-1

IMG_2FA54B320BB9-1

IMG_F125C3474E0C-1

IMG_1E254B793B1F-1 2

### CODE REVIEW

**Comment by lonkle** [comment]
@ianclawson Why is the SNES controller silly small compared to the rest of them? Is it some kind of "width and icons scale as needed" automatic thing - and if so, should we increase the width so all controllers are full size?

**Comment by ianclawson** [comment]
@lonkle good question! It's because there (purposefully) isn't room on the screen to show every console, so as the icons go off into the side they shrink. Essentially it's a built in part of PageControl to show "there's more pages over here!"

When there isn't more pages than there is room to show, then they all are given the same weight and size.

This video demonstrates it best:

https://user-images.githubusercontent.com/18663382/126700845-48ce8bc3-b9aa-4298-ae37-aa8628c96d5c.mov

**Comment by lonkle** [comment]
Oh, perfect, that's what it looked like (auto-scaling), but I wanted to be sure. Thank you for the video. ☺️ 

You said that it is "purposeful" to not have enough room on the screen? Is this forward thinking with future consoles in mind and, given that, do you think the current "page dots space width" is good to go as far as User Interface goes? It did look good from the video, I just wasn't sure if that width was customizable or if iOS "handles it".

**Comment by ianclawson** [comment]
> Oh, perfect, that's what it looked like (auto-scaling), but I wanted to be sure. Thank you for the video. ☺️
> 
> You said that it is "purposeful" to not have enough room on the screen? Is this forward thinking with future consoles in mind and, given that, do you think the current "page dots space width" is good to go as far as User Interface goes? It did look good from the video, I just wasn't sure if that width was customizable or if iOS "handles it".

@lonkle So it was purposefully only so far as I wanted to see what it looked when autoscaling happens. The width is totally customizable, so I arbitrarily added constraints to shorted the width of the PageControl like so in this PR:

```swift
self.pageControl.leadingAnchor.constraint(equalTo: (self.navigationController?.toolbar.leadingAnchor)!, constant: 35).isActive = true
         self.pageControl.trailingAnchor.constraint(equalTo: (self.navigationController?.toolbar.trailingAnchor)!, constant: -35).isActive = true
```

I like the way it looked, so I left it there 🙃 

I will admit that the icons did previously fit there without scaling, so I only added the constraints out of curiosity to "force" the effect to happen. Here's what it looks like with all current officially supported beta systems and without those ui constraints:

IMG_3DBD4E326924-1

I am more than happy to remove the constraints if this is the preferred look 🙂 Fortunately either way, we know it looks good should more systems be added to Delta and Delta keeps this UI paradigm!

**Comment by lonkle** [comment]
Okay, I love that you did this to make sure it was future-proof. It can accommodate any number of systems and from the video you took, it still looks and feels smooth.

But settling on a max-width is hard. Now personally, I think it looks better flush with the max width set to see all icons at full-size, and love that it's future-proofed in the way shown. My main pro with making the icons full size is because you should be able to tap each controller as per the API to go immediately to that console.

**Comment by lonkle** [comment]
Been testing this all out and it's been working great. The only note I have is that in landscape mode - space isn't adjusted for the new icon sizes. Two solutions:

• Use a bottom "page dot" border, just like vertical orientation
• Pad the bottom of the page in landscape

What do you think @ianclawson?

**Comment by ianclawson** [comment]
@lonkle I've updated this PR with some goodies:
- found out where the toolbar was being hidden in landscape orientation and fixed it. I agree with you, it looks much better. And judging by the implementation I now believe it was a side-effect and not actually intended, so I'm glad it's changed.
- reduced the left/right padding so that more icons will appear on screen at a time.
- updated the size of the controller icons to be more reasonable at just a tad smaller.

Now, one thing we can't really avoid is having the UI that appears when dragging a touch across the toolbar to NOT be larger then the toolbar. I think if we don't like this UI, we should disable the ability to continuously update the update by dragging altogether. See pictures for what I'm talking about.

IMG_DE1155EF467B-1

IMG_C886BA251D6B-1

IMG_35E2852EAB72-1

IMG_2F98FEF3222F-1

**Comment by lonkle** [comment]
Continuous scrolling feels non-negotiable. It's the only way to fast travel from console to console. The discreet border wasn't an issue, it was the fact that the icons were a few pixels too high making the "continuous border" clash with the top of the "icons bottom" border.

**Pull request closed without merging**
