### PR TITLE
adds support for changing the app icon

### PR DESCRIPTION
**Pull request by kylegrieder**

### CODE REVIEW

**Comment by kylegrieder** [comment]
I should note: the project file has to be changed because binary assets (image files) are added to the project.

**Comment by lonkle** [comment]
Incorporated your custom icons into a newer PR that added that icon changing feature. Thank you for making these alternative icons!

**Comment by kylegrieder** [comment]
Cool, glad to see this finally added to Delta.

**Comment by lonkle** [comment]
Same, it'll be a cool feature. Here's the PR that I added your icons too if you wanna follow it: https://github.com/rileytestut/Delta/pull/130

**Pull request closed without merging**
