### PR TITLE
Feature: Change App Icon Functionality

### PR DESCRIPTION
**Pull request by ianclawson**
Implements the ability to change app icon as discussed in the AltStore Discord, using the icons provided therein.

Relevant Trello Card: https://trello.com/c/lBhuBBj4/174-qol-provide-a-series-of-app-icons-in-app-to-switch

### CODE REVIEW

**Comment by lonkle** [comment]
More Alternative Icons by @kylegrieder attached.

[Kyle Grieder's Alternate Delta Icons.zip](https://github.com/rileytestut/Delta/files/6722139/Kyle.Grieder.s.Alternate.Delta.Icons.zip)

**Comment by ianclawson** [comment]
IMG_5710B9BEBED4-1

IMG_6565BC0324B1-1

**Comment by lonkle** [comment]
@ianclawson This is absolutely perfect, would it be difficult to throw in a commit to round the corners (like iOS does to it's icons) to show what the user exactly what the icon will look like?

**Comment by ianclawson** [comment]
> @ianclawson This is absolutely perfect, would it be difficult to throw in a commit to round the corners (like iOS does to it's icons) to show what the user exactly what the icon will look like?
> 
> And maybe "Pride 1" and "Pride 2" could be "Pride" and "Pride (Gradient)" - or do ya think the numbering looks better?

Appreciate the feedback! I much prefer your suggested "Pride" and "Pride (Gradient)" so I'll update accordingly 👍 

For the rounded corners, I'll give it a shot! It's def possible using a custom cell (right now I'm using a default one) but I'll first try an approach using the default cell to see if I can make any gains there without extending the PR much more.

**Comment by ianclawson** [comment]
@lonkle updated! Adding the App Icon curve is such a nice touch -- I'm mad I didn't think of it! 😂 Thanks for the recommendation.

**Comment by lonkle** [comment]
It looks great! And this is why we work on things together! Two pairs of eyes. 😉 I updated the Trello card cover image with your new screenshot and it looks awesome!

**Comment by ianclawson** [comment]
Closing this PR (kinda) in favor of another PR I will be opening in the next few days.

I just realized I'm working on 3 separate smaller QoL enhancements that all have to do with configuring the app's appearance in some way, and so realized from a UI perspective it makes sense to consolidate those into an "Appearance Settings" screen, therefore it would be cleaner to wrap all of those into a single PR.

I'm halfway through the final enhancement now, so I'm hoping to have the other PR ready by the end of the week 🤞

**Pull request closed without merging**
